# torvpn-win default profile
[tun]
interface = "torvpn"
mtu = 1400

[tor]
socks_port = 9050
dns_port = 5353
control_port = 9051
use_bridges = false
client_transport_plugin = ""
bridges = []
tor_path_hint = "C:/tools/tor-expert/tor/tor.exe"

[tun2socks]
binary = "C:/tools/tun2socks/tun2socks-windows-amd64-v3.exe"

[proxy]
enabled = false
rotation = "off"
proxies = []

[exit]
countries = ["fr"]
strict = true

[pqc]
enabled = false
algo_sig = "dilithium2"
algo_kem = "kyber1024"

[hop]
enabled = false
randomize = false
loop_forever = true
jitter = "0s"

[[hop.sequence]]
duration = "20m"
exit_countries = ["us"]
proxy = "next"

[[hop.sequence]]
duration = "15m"
exit_countries = ["de"]
proxy = "socks5://203.0.113.42:1080"

[status]
enabled = true
listen = "127.0.0.1:18081"
